### ISSUE TITLE
Error in test.py 

### ISSUE THREAD

**Issue by xiao-tai** [malshaV/sar_transformer#4]
Traceback (most recent call last):
  File "D:\Project\Pycharm Project\sar_transformer-main\test.py", line 81, in <module>
    pred_im = model(x)
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 158, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 175, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 44, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 36, in scatter
    res = scatter_map(inputs)
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 23, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\scatter_gather.py", line 19, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\_functions.py", line 95, in forward
    streams = [_get_stream(device) for device in target_gpus]
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\_functions.py", line 95, in <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "D:\Software\Anaconda3\envs\PyTorch\lib\site-packages\torch\nn\parallel\_functions.py", line 122, in _get_stream
    if _streams[device] is None:
IndexError: list index out of range

line 81 in test.py ----pred_im = model(x), the x's shape is (1, 1, 512, 512)
I don't know why the _streams[device] is None

**Comment by xiao-tai** [comment]
I add "model = nn.DataParallel(model, device_ids=[0]).cuda()" before "model.load_state_dict(torch.load(loaddirec))".
